name: Python Application

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install black flake8

      - name: Lint with Black
        run: |
          black --check .

      - name: Lint with flake8 on tests and backend folders
        run: |
          flake8 tests/ backend/

  build:
    environment: Development
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      REDIS_URL: ${{ secrets.REDIS_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r .github/workflows/requirements.txt

      - name: Test with pytest and generate coverage report
        run: |
          pytest --cov=backend --cov-config=.coveragerc --cov-report=term-missing tests/
